# Generated by Django 2.1.5 on 2019-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190126_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to='images/', width_field=800),
        ),
    ]
