# Generated by Django 2.1.5 on 2019-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190126_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
    ]
